### ISSUE TITLE
Edge table not found in weakly_connected_component function

### ISSUE THREAD

**Issue by pkoppstein** [cwida/duckpgq-extension#148]
### What happens?

```
Invalid Error: Table edges not found in property graph my_graph
```

Note: [the documentation ](https://duckpgq.notion.site/Graph-functions-c6678b8a9a9a4bd7ab42166aa727bace) indicates the `"<edge table>"` should be used:
```
weakly_connected_component(<pg>, <vertex table>, <edge table>)
```
### To Reproduce

```
LOAD duckpgq;

CREATE or replace TABLE edges (
    source INTEGER,
    target INTEGER
);

-- Insert some sample data (directed edges)
INSERT INTO edges VALUES (1, 2), (2, 3), (4, 5), (2, 4), (10,11);

CREATE OR REPLACE TABLE nodes AS
   (SELECT DISTINCT id FROM
    (SELECT DISTINCT source AS id FROM edges
    UNION
    SELECT DISTINCT target AS id FROM edges
    ) );

CREATE OR REPLACE PROPERTY GRAPH my_graph
  VERTEX TABLES (
   nodes LABEL nodes
 )
  EDGE TABLES (
    edges SOURCE KEY (source) REFERENCES nodes (id)
          DESTINATION KEY (target) REFERENCES nodes (id)
          LABEL knows
  );

SELECT * FROM weakly_connected_component(my_graph, nodes, edges);
```

### OS:

macOS

### DuckDB Version:

v1.0.0

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### How did you load the extension?

Latest version

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Dtenwolde** [comment]
You gave the edge table `edges` the label `knows`. The `weakly_connected_components` table function now won't work with `edges`, but instead expects `knows`. This is a bit confusing, especially as the error message is not helpful.  

```sql
SELECT * FROM weakly_connected_components(my_graph, nodes, knows); 
```

This should work 🙂 

I'll rework the error message
