### ISSUE TITLE
Support property graph creation over views

### ISSUE THREAD

**Issue by Dtenwolde** [cwida/duckpgq-extension#159]
### What happens?

As highlighted in #158 it is currently not possible to create a property graph containing a view. Internally views are ViewCatalogEntry instead of TableCatalogEntry, which we rely on to figure out whether the PK-FK relationship is correct for the vertex tables and edge tables. Perhaps we can do something to support views as well. Or we should choose to not support this, but it is worth an investigation at least. 

### To Reproduce

-

### OS:

macOs 13 - Apple M1 Pro

### DuckDB Version:

v1.1.2

### DuckDB Client:

CLI

### Full Name:

Daniel ten Wolde

### Affiliation:

CWI

### How did you load the extension?

Built from source

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Dtenwolde** [comment]
Currently not going to pursue this as we need to know the schema for the property graph. If there is enough request I might reconsider in the future

**Comment by zolero** [comment]
I'm also encountering this error in NodeJS using duckdb 1.1.3, really don't know how to solve this... Steps to reproduce.

```ts
import { createDirectory } from "@yoda-assistant/utils";
import { afterAll, beforeAll, describe, it } from "vitest";

import { Database } from "@/duckdb";

describe("geocoding", () => {
    let db: Database;

    beforeAll(async () => {
        await createDirectory("tmp");

        db = await Database.create("tmp/graph-test-db.db", {
            access_mode: "read_write"
        });

        // Install and load the Arrow extension
        await db.run(`INSTALL arrow; LOAD arrow;`);
        await db.run(`INSTALL fts; LOAD fts;`);
        await db.run(`INSTALL duckpgq FROM community; LOAD duckpgq;`);
        await db.run(`UPDATE EXTENSIONS;`);
    });

    it("duckpgq function should return expected string", async () => {
        const res = await db.all("SELECT extension_name, installed, description FROM duckdb_extensions();");
        console.log(res);
    });

    it("should create a temporary schema", async () => {
        await db.run(`
            CREATE TABLE Person as SELECT * FROM read_json('assets/persons.json');
            CREATE TABLE Person_knows_person as  SELECT * FROM read_json('assets/persons-edges.json');
        `);
    });

    it("should return the number of rows in the Person table", async () => {
        await db.exec(` CREATE PROPERTY GRAPH snb
          VERTEX TABLES (
            Person
          )
          EDGE TABLES (
            Person_knows_person SOURCE KEY (Person1Id) REFERENCES Person (id)
                                DESTINATION KEY (Person2Id) REFERENCES Person (id)
            LABEL Knows
        );`);
    });

    it("should return a graph result", async () => {
        const res = await db.all(`SELECT CAST("element_id(p)" AS "JSON") as test FROM GRAPH_TABLE (snb
                                                                                                                                           MATCH p = ANY SHORTEST (a:Person WHERE a.firstName = 'Jan')-[k:knows]-> +(b:Person)
            COLUMNS (element_id(p), vertices(p), edges(p), path_length(p), b.firstName)
                                                                                                                          )
                                  ORDER BY firstName
                                      LIMIT 5;

        `);
        console.log(res);
    });

    afterAll(async () => {
        await db.close();
    });
});
```

**Comment by peterboncz** [comment]
thanks for the repro, but what error are you actually getting?

Just to add to Daniel's remark on not supporting views: DuckPGQ also uses ROWIDs to quickly construct a CSR data structure with dense node and vertex numbers (used in path finding). And VIEWs in DuckDB do not have ROWIDs, as this is coupled to table storage.
