### ISSUE TITLE
Compilation failure 

### ISSUE THREAD

**Issue by dentiny** [cwida/duckpgq-extension#174]
### What happens?

Compilation failure example:
```
/home/ubuntu/duckpgq-extension/src/core/functions/function_data/weakly_connected_component_function_data.cpp:33:10: error: could not convert 'result' from 'unique_ptr<duckpgq::core::WeaklyConnectedComponentFunctionData,default_delete<duckpgq::core::WeaklyConnectedComponentFunctionData>,[...]>' to 'unique_ptr<duckdb::FunctionData,default_delete<duckdb::FunctionData>,[...]>'
   33 |   return result;
      |          ^~~~~~
      |          |
      |          unique_ptr<duckpgq::core::WeaklyConnectedComponentFunctionData,default_delete<duckpgq::core::WeaklyConnectedComponentFunctionData>,[...]>
```

Similar to pg_duckdb issue: https://github.com/duckdb/pg_duckdb/discussions/455

### To Reproduce

`make debug` on my platform fails, platform information see below.

### OS:

ubuntu, x86_64

### DuckDB Version:

1.1.3

### DuckDB Client:

N/A

### Full Name:

Hao

### Affiliation:

N/A

### How did you load the extension?

Built from source

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Dtenwolde** [comment]
Fixed in #173
