### ISSUE TITLE
Binder Error when selecting from non-existent relation

### ISSUE THREAD

**Issue by dbeatty10** [cwida/duckpgq-extension#95]
### What happens?

Selecting from a non-existent table gives the following error:

```
Error: Binder Error: Unable to find DuckPGQ Parse Data
```

But I expected this error instead:

```
Error: Catalog Error: Table with name table_that_does_not_exist does not exist!
Did you mean "temp.information_schema.tables"?
LINE 1: select * from table_that_does_not_exist;
```

### To Reproduce

Selecting from a non-existent table gives an error:

```shell
$ ./build/release/duckdb
D select * from table_that_does_not_exist;
```

Output:
```
Error: Binder Error: Unable to find DuckPGQ Parse Data
```

Opening the same file with duckdb and re-running that query gives the expected error message:

```shell
$ duckdb db.db
D select * from table_that_does_not_exist;
```

Output:
```
Error: Catalog Error: Table with name table_that_does_not_exist does not exist!
Did you mean "temp.information_schema.tables"?
LINE 1: select * from table_that_does_not_exist;
```

Here's my version of duckdb (without the pgq extension installed):

```shell
duckdb --version
```

Output:
```
v0.10.0 20b1486d11
```

### Environment

OS: macOS
Version: duckdb-pgq v0.10.0 3e6d77b923

After following [these](https://duckpgq.notion.site/Getting-Started-29eda93a97b140e1861614cce1f5498c) installation instructions, here is my current version:

```
$ ./build/release/duckdb --version

v0.10.0 3e6d77b923
```

**Comment by Dtenwolde** [comment]
Fixed in https://github.com/cwida/duckpgq-extension/tree/95-binder-error-when-selecting-from-non-existent-relation waiting to merge 

Somewhat related to #96 as `select * from table_that_does_not_exist;` now throws the same error where "source" gives a syntax error
